name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  deploy-to-rainfall-discordbot:
    runs-on: self-hosted
    steps:
      - name: Update code from Git
        working-directory: /home/ryan/projs/bot/BonBot
        run: |
          echo "Fetching latest changes..."
          git fetch --all
          echo "Pulling latest changes..."
          git pull
        
      - name: Restart BonBot service
        run: |
          echo "Restarting BonBot..."
          sudo /bin/systemctl restart bonbot.service
