name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  run-local:
    runs-on: self-hosted
    steps:
      - run: cd /home/ryan/projs/bot/BonBot && git fetch && git pull
      - run: sudo /bin/systemctl restart bonbot.service
